//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DML
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsStatus
    {
        public int ID { get; set; }
        public System.DateTime StatusDataFrom { get; set; }
        public decimal GoodAmount { get; set; }
        public int GoodOperationID { get; set; }
        public int GoodID { get; set; }
    
        public virtual GoodOperationType GoodOperationType { get; set; }
        public virtual Goods Goods { get; set; }
    }
}
